### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by chuxiang93** [sdw95927/Comprehensive-analysis-of-lung-cancer-pathology-images#2]
Hi, 
   I have  two questions. First, I checked the data on TCGA, but I did not see the label, did you label the data by yourself. Second, I applied for data on the NLST, but I saw on the website that I need to mail my own hard disk to copy data, is that right?

Thanks.

**Comment by sdw95927** [comment]
Hi, 

1) Yes we have pathologists to label the data through ImageScope.

2) Sorry that I'm not the person who collected NLST data. But do what the NLST website asked should be fine. You can also directly contact them.

Thanks!

**Comment by Tato14** [comment]
Hi @tianmaliuixing,
Could you please share the link and the way to obtain the WSI and the xml files of the NLST data in case you find the way?
Thanks!

**Comment by sdw95927** [comment]
> Hi @tianmaliuixing,
> Could you please share the link and the way to obtain the WSI and the xml files of the NLST data in case you find the way?
> Thanks!

I think the way to obtain WSI is clear in https://biometry.nci.nih.gov/cdas/learn/nlst/images/. xml file can be annotated and generated through using ImageScope. Thanks!

**Comment by lsm-sunny** [comment]
Hi,how can I get the  NLST dataset,could you share the link with me?Thanks!
