### ISSUE TITLE
The "log.txt" is missing while running 1_generatePatches 

### ISSUE THREAD

**Issue by Shokry1** [sdw95927/Comprehensive-analysis-of-lung-cancer-pathology-images#3]
How to obtain the "log.txt" file. Is it included with the dataset? Also, Are there any missing files other than this one?

**Comment by sdw95927** [comment]
"log.txt" is only used to record which slides you are going to extract patches from. You can easily create "log.txt" by recording the path/filenames of your slides or modify the script a little bit.
